export const LOGIN = '/login'
export const SERVICE = '/services'
export const SERVICE_REGISTER = '/service-register'
export const MA_VA = '/map-va-insert'
export const CUSTOMER_ACCOUNT = '/customer-account'
export const CURRENT_ALIAS_ID = '/current-alias-id'
export const VA_REGISTER = '/register-va'
// export const VA_REGISTER = '/register-va'
export const VA_UPDATE = '/update-va'
export const VA_DELETE = '/delete-va'
export const CUSTOMERZ_REGISTER_LIST = '/customer-list'
export const DELETE_LIST_ADDED = '/delete-map-va'
export const MENU_LIST = '/menu'
export const IMAGES = '/images'
export const EXCHANGE = '/exchange'

